import axios from "axios";
import fs from "fs";
import ApiGenerator from "./apis";
import DefinitionGenerator from "./definitions";

const baseUrl = "https://api.staging.gremlin.com/v1/";

axios.get(`${baseUrl}swagger.json`).then(async (response) => {
  const data = response.data;

  const { paths, definitions } = data;

  async function folderCleanup(folder: string) {
    const files = fs.readdirSync(folder);
    for (let i = 0; i < files.length; i++) {
      const file = files[i];
      if (fs.lstatSync(`${folder}/${file}`).isFile()) {
        const allFileContents = fs.readFileSync(`${folder}/${file}`, "utf-8");
        if (
          allFileContents.indexOf(
            `// This file is autogenerated - do not change`
          ) === 0
        ) {
          fs.unlinkSync(`${folder}/${file}`);
        }
      }
    }
  }

  async function run() {
    await folderCleanup("generated");
    const defGen = new DefinitionGenerator();
    const apiGen = new ApiGenerator(defGen);

    defGen.parseDefinitions(definitions);
    apiGen.parsePaths(paths);
  }

  run();
});
